on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: naveensrinivasan/ghaction@main
        with:
          who-to-greet: 'Mona the Octocat'
