on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        uses: actions/checkout@v3
        uses: naveensrinivasan/ghaction@v1
        with:
          who-to-greet: 'Mona the Octocat'
