on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Hell world action
        uses: naveensrinivasan/ghaction@v1
        with:
          who-to-greet: 'Mona the Octocat'
